### ISSUE TITLE
is this Cloudflare Pages compatible?

### ISSUE THREAD

**Issue by TimKieu** [razshare/sveltekit-sse#50]

**Comment by razshare** [comment]
Hello @TimKieu ,
it used to not support distributed systems, but now it should.
I haven't had the change to try it yet though, so you feedback would be much appreciated.

Issue https://github.com/razshare/sveltekit-sse/issues/45 discusses this exact problem, more specifically in https://github.com/razshare/sveltekit-sse/issues/45#issuecomment-2105650601 section `Main Issue`, I haven't got any more feedback on this topic since then, so it would be interesting to know if it works fine and issues people are facing with that type of environment.

It goes without saying that you can't store local state when it comes to distributed systems, you must use some external distributed db or something like that if you want your data to be consistent.

---

Let me know if this addresses your question.

**Comment by TimKieu** [comment]
@razshare Thanks much.
I happily confirm that your SSE kit runs well on CloudFlare Pages!

**Comment by aristelecom** [comment]
Hi @TimKieu, I'm glad to know that you managed to get it to work in cloudflare, I've been trying for a couple of hours to get it to work in vercel but unfortunately due to its limitations it is not possible.

Say this, I'm trying to deploy a test project on cloudflare but I'm experiencing some problems, can you share more information about how you got it to work on cloudflare? 

I attach my test repository: https://github.com/aristelecom/sveltekit-sse-cloudflare
