### ISSUE TITLE
How can I use this with Svelte 5 runes?

### ISSUE THREAD

**Issue by kristianmandrup** [razshare/sveltekit-sse#54]
I would like aggregate the SSE events in a messages state/store. Would I run the source in an onMount or $effect?
It is unclear how to use it with stores

```ts
	const connection = source('/events/app');
	const channel = connection.select('project');
``` 

```ts
<script>
	let messages = $state<string[]>([]);

	messageStore.addMessage($json);

	messageStore.subscribe((value) => {
	 	messages = value;
	 });
</script>

<div>
	<h1>Projects</h1>
	<h2>Messages</h2>
	{#if messages.length === 0}
		<p>No messages yet.</p>
	{:else}
		<ul>
			{#each messages as message}
				<li>{message}</li>
			{/each}
		</ul>
	{/if}
</div>
```

**Comment by razshare** [comment]
Hello @kristianmandrup , I'm not very familiar with Svelte 5 and I plan to wait until it's actually released to do any work specific to it.

That being said, in Svelte 4 you would just have to do this

```svelte
<script>
  import { source } from 'sveltekit-sse'
  import { messageStore } from 'message-store'
  const connection = source('/events/app')
  const message = connection.select('message')
  $: messageStore.addMessage($message)
</script>

// Your markup goes here.

```

I'm assuming the equivalent in Svelte 5 is something like this

```svelte
<script>
  import { source } from 'sveltekit-sse'
  import { messageStore } from 'message-store'
  const connection = source('/events/app')
  const message = connection.select('message')
  $effect(function run() {
    messageStore.addMessage($message)
  })
</script>

// Your markup goes here.

```

I haven't tested it though.
I do remember the Svelte team saying at some point that stores will interact with runes as they normally interact with the current reactive system in Svelte 4, so it would be a breaking change on their part if this doesn't work.

---

Let me know if this answers your question.

**Comment by kristianmandrup** [comment]
Thanks a lot for your answer. For now I seem to have it working using the following pattern:

```ts
	const transformed = channel.transform(function run(data) {
		if (data === '') return;
		// TODO: parse json
		return `${data}`;
	});

	let projects = $state<ProjectPayload[]>([]);
	let lastMessage = $state<string>('');

	transformed.subscribe((value: string) => {
		if (!value) return;
		lastMessage = value;
                // TODO: move to transform function
		const json = JSON.parse(value);
		const { source, model, action, data } = json;
		if (model !== 'project') {
			console.log('not a project event');
			return;
		}
		const project = data;
		// TODO: depending on the event, add, remove or update the project
		projects = [...projects, project];
	});

	import { getToastState } from '$lib/toast-state.svelte';

	const toastState = getToastState();

	const toastMap = new Map<string, unknown>();

	$effect(() => {
		const message = lastMessage;
		if (!message) return;

		const json = JSON.parse(message);
		const { data } = json;
		if (!data) {
			console.error('missing data', json);
		}
		const { name, description } = data;
		if (!name) {
			console.log('missing name', data);
			return;
		}
		// already processed
		if (toastMap.get(name)) {
			console.log('already made toast for', name);
			return;
		}
		toastMap.set(name, data);
		toastState.add(name, description);
	});
```

Currently overly verbose and complicated, but it gets the job done. The key was to simply subscribe to the readvalue store returned by transform

```ts
transformed.subscribe((value: string) => { ... })
```

Then from there I could set a `$state` with the value and work from there. I'm sure there is a much simpler way.
Btw, I had an issue with the first message received from SSE always being an empty string for some reason, but it might well be an issue with my internal logic, such as `undefined` being sent as empty string?

**Comment by razshare** [comment]
> Btw, I had an issue with the first message received from SSE always being an empty string for some reason, but it might well be an issue with my internal logic, such as undefined being sent as empty string?

That is expected behavior, the first value is always empty because it takes time to actually open the connection to the server.

It's either that or force userland to deal with a `Promise<string>` and `{#await}` in the markup.

A third solution would be initializing the value in SSR but that would mean your server would have to open a connection to itself to read the value, which is a waste of resources and will probably slow down the SSR itself by a lot, especially in a clouod environment where you're not 100% the node doing the SSR will actually connect to itself. It could connect to a different twin node and slow down things even more.

**Comment by WarningImHack3r** [comment]
Any update on a new major version that uses runes instead of stores? It's not blocking but it'll be a great improvement

**Comment by razshare** [comment]
Hello @WarningImHack3r ,

I've had a few attempts at trying to convert the usage of stores into runes since Svelte 5 came out.

I wasn't really happy with the outcome, specifically the api is quite more clunky when it comes down to observing new incoming data outside of the Svelte Template.

To achieve the same results it is required to use the `$effect` rune, which ironically enough, the Svelte Team discourages using.

Just because you reminded me of this, I'll give it another shot this weekend, I'll try come up with something, but stores are pretty damn good at this type of stuff, so it'll be hard to come up with something better, imo.

I'll update you, have a good day.

**Comment by WarningImHack3r** [comment]
@razshare thanks for your reply!
`$effect` are indeed discouraged, but not prohibited, it's fine if you don't have any other way ^^
Stores are good but will come to an end in the next Svelte majors (we have still the time to see it coming though), and are also far less granular and efficient than runes!

Good luck with your attempts, take your time!

(side-note: I think this issue should be closed as "won't fix"/"not planned" instead of "solved" for the time being, even though it'll eventually be solved when you drop a rune-powered version)

**Comment by razshare** [comment]
Hello again @WarningImHack3r 

I've done some more attempts.

I want to address a two things first, though.

> Stores are good but will come to an end in the next Svelte majors 

As far as I know, that is not the case.

The old component based reactivity system is marked for deprecation and will be removed in the next major version.

Store were never on the table for removal, they are a separate matter.

I believe that misconception comes from Rich saying at some point that "we're not sure about stores" (I'm paraphrasing).

> and are also far less granular and efficient than runes

It's actually the opposite, from what I've been discovering slowly, at least in this specific use case.

### Why?

Because runes don't have a baked in start-stop-notifier mechanism, which this library uses a lot.

One of the reason why this library's API is simple to use is that we don't have to worry about subscriptions at all, unless you're using the raw API `.subscribe()`, and even then if handled properly unsubscribes are detected automatically by the library.

Stores have a baked in start-stop-notifier mechanism, which I'm willing to bet is the main reason why the Svelte core team have not dropped stores.

See https://svelte.dev/docs/svelte/svelte-store#StartStopNotifier

But that's not all, because from this simple feature of stores, a whole new bunch of other things are being handled automatically in this library.

One other example is stream sharing.

See https://github.com/razshare/sveltekit-sse?tab=readme-ov-file#other-notes

Basically, whenever you connect to the same server event dispatcher with `source()`, instead of creating a new connection, it will use an already existing one; it's caching connections.

That is actually handled by Svelte's stores, automatically.

There are other minor issues, like the lack of dedicated type hints for rune states, but that's more of a devx issue than a pragmatic one.

I know some people make a big fuss about the lack of proper types in rune state, but honestly it's solvable by adopting a naming standard, like prefixing rune states with `state_` or `rune_`, which some people were already doing before with stores, prefixing them with `store_`.

Regardless, I really don't think runes are a good fit for this library, and the Svelte team themselves seem to agree when saying 

> Stores are still a good solution when you have complex asynchronous data streams or it’s important to have more manual control over updating values or listening to changes.

https://svelte.dev/docs/svelte/stores#When-to-use-stores

I guess if we ever get a rune that solves this specific issue, which is: providing a start-stop-notifier mechanism, runes could be a good fit.

In short, we really need to know when components unsubscribe from a state, otherwise we would have to add a lot of boilerplate into the API, which I'm not willing to do because I want this library to keep things as simple as possible; I think that's what we would call "the Svelte way".

### Other considerations

If you really want to use runes for consistency in your project, you can always use `.subscribe()` to set update a `$state`, or the other way around, you could use `$derived` to derive the state from your store.

**Comment by WarningImHack3r** [comment]
@razshare thanks a lot for this detailed explanation! Your points are absolutely fair.
I was pushing/asking for this migration for long term maintenance purposes after the big shift Svelte 5 introduced with runes.
However, despite being replaceable in some cases, it’s absolutely okay to keep using it because they aren’t going anywhere for now.
I can safely start using your library for my Svelte 5 website. Thanks for the lib and your investigation and explanations!
